language: go
go:
  - tip
os:
  - linux
  - osx
env:
  global:
    GOENV_ROOT: $HOME/gopath/src/github.com/kaneshin/goenv
    GO_VERSION: 1.7
    GAE_VERSION: gae-1.9.46
install:
  - $GOENV_ROOT/bin/goenv install $GO_VERSION
  - $GOENV_ROOT/bin/goenv install $GAE_VERSION
script:
  - test -d $GOENV_ROOT/versions/$GO_VERSION
  - test -d $GOENV_ROOT/versions/$GAE_VERSION
  - |
    $GOENV_ROOT/bin/goenv global $GO_VERSION && $GOENV_ROOT/bin/goenv rehash && \
    test -x $GOENV_ROOT/shims/go && test -x $GOENV_ROOT/shims/godoc && test -x $GOENV_ROOT/shims/gofmt
  - |
    $GOENV_ROOT/bin/goenv global $GAE_VERSION && $GOENV_ROOT/bin/goenv rehash && \
    test -x $GOENV_ROOT/shims/goapp && test -x $GOENV_ROOT/shims/godoc && test -x $GOENV_ROOT/shims/gofmt
