#!/usr/bin/env bash
#!/usr/bin/env bash
# Summary: Complete commands
#
# Usage: goenv completions <command>

# Bomb out if we hit an error, ever
set -e

# Verbose output in debug mode
[ -n "$GOENV_DEBUG" ] && {
  set -x
}

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  goenv-help --usage completions >&2
  exit 1
fi


# Provide goenv completions
if [ "$COMMAND" = "--complete" ]; then
  exec goenv-commands
fi

COMMAND_PATH="$(command -v "goenv-$COMMAND" || command -v "goenv-sh-$COMMAND")"

# --help is provided automatically
echo --help

if grep -iE "^([#%]|--|//) provide goenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
