#!/usr/bin/env bash
# Summary: Show the current Go version and its origin.

# Bomb out if we hit an error, ever
set -e

# Verbose output in debug mode
[ -n "$GOENV_DEBUG" ] && {
  set -x
}


if [ -n "$GOENV_VERSION_ORIGIN" ]; then
  echo "$GOENV_VERSION_ORIGIN"
elif [ -n "$GOENV_VERSION" ]; then
  echo "GOENV_VERSION environment variable"
else
  goenv-version-file
fi
