#!/usr/bin/env bash
# Summary: Install a version of Go.
#
# Usage: goenv install <version>
#
# Versions should be in the form of N.N.N

# Bomb out if we hit an error, ever
set -e

# Verbose output in debug mode
[ -n "$GOENV_DEBUG" ] && {
  set -x
}

# Pull the desired version out of ARGV
version="$1"
if [ ${version} = '--list' ]; then
    echo 'Available versions:'
    curl --silent  https://raw.githubusercontent.com/GoogleCloudPlatform/gradle-appengine-plugin/master/RELEASE_NOTES.md | perl -n -e '/^### Versions? ([0-9\.]+) / && print "gae-", $1, "\n"'
    curl --silent https://golang.org/doc/devel/release.html | perl -n -e '/^(go|Go )([0-9\.]+) / && print $2, "\n"' | sort -nr | uniq
    exit 0
elif [[ ${version} =~ ^(gae|appengine|goappengine)- ]]; then
  # Google App Engine
  version=gae-${version/$BASH_REMATCH}
fi
version_dir="$GOENV_ROOT/versions/$version"

# stash the pwd
OLDPWD=$(pwd)

platform="$(uname -s | tr '[:upper:]' '[:lower:]')"

if [ "$(uname -m)" = "x86_64" ]; then
  arch="amd64"
else
  arch="386"
fi

if [ "$platform" = "darwin" ]; then
  # Since go version 1.2, osx packages were subdivided into 10.6 and 10.8
  case "$version" in
  1.2*|1.3*|1.4|1.4.[12] )
    if [ "$(uname -r)" \> "12" ]; then
      extra="-osx10.8"
    else
      extra="-osx10.6"
    fi
    ;;
  esac
fi

download=""
if [[ ${version} =~ ^gae- ]]; then
  aeversion=${version/$BASH_REMATCH}
  download="https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_${platform}_${arch}${extra}-${aeversion}.zip"

else
  download="https://storage.googleapis.com/golang/go${version}.${platform}-${arch}${extra}.tar.gz"
fi

# Can't get too clever here
set +e

code="$(curl --silent -LI -w '%{http_code}' -o /dev/null ${download})"
if [ "404" = ${code} ]; then
  echo "Not found: ${version}"
  exit 1
fi

# Make the version dir and get in there
mkdir -p "$version_dir"
cd "$version_dir"

archive="$(basename $download)"
echo "Downloading ${archive}..."
echo "-> ${download}"

# Download binary tarball and install
# Linux downloads are formatted differently from OS X
ext="${archive##*.}"
(
  curl --silent -L -f "$download" > "/tmp/$archive"
  if [ "zip" = $ext ]; then
    unzip "/tmp/$archive" > /dev/null
    for file in go_appengine/*; do
      rm -fr "$(basename $file)" && mv $file .
    done
    rm -rf go_appengine
  else
    tar zxf "/tmp/$archive" --strip-components 1
  fi
  rm "/tmp/$archive"
) || {
  cd $OLDPWD
  rmdir "$version_dir"

  echo "goenv: unable to install Go \`${version}' from binary, download not available at ${download}"
  exit 1
}

echo "Installed ${version} to ${version_dir}"
cd $OLDPWD
